name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  build_ios:
    runs-on: macos-latest  # macOS runner for iOS builds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release
