name: Release

on:
  release:
    types:
      - created

jobs:
  release_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/

  release_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ios --release

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/ios/iphoneos/

  merge_assets:
    runs-on: ubuntu-latest
    needs:
      - release_android
      - release_ios

    steps:
      - name: Merge Release Assets
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: |
            release_android/app-release/*
            release_ios/app-release/*
